version: '3.8'

services:
  smtp-mcp-server:
    build: .
    ports:
      - "3008:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
      - LOG_LEVEL=info
    volumes:
      # Mount config directory for persistent SMTP configurations
      - ./config:/app/config
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3007/api/list-tools"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - smtp-mcp-server
  #   restart: unless-stopped

networks:
  default:
    name: smtp-mcp-network
