services:
  smtp-mcp-server:
    build: .
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
      - LOG_LEVEL=info
      - DATABASE_TYPE=sqlite
      - SQLITE_DB_PATH=./data/smtp-server.db
      # SMTP Environment Variables (OPTIONAL - server now supports dynamic SMTP per request)
      # Uncomment if you want default SMTP fallback credentials:
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_PORT=587
      # - SMTP_SECURE=false
      # - SMTP_USER=your-email@gmail.com
      # - SMTP_PASS=your-app-password
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - API_KEY=your-api-key-change-this
      - ENABLE_TEMPLATES=true
      - ENABLE_RATE_LIMITING=true
      - ENABLE_BULK_EMAIL=true
      - ENABLE_SWAGGER=true
    volumes:
      # Mount config directory for persistent SMTP configurations
      - ./config:/app/config
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
      # Mount data directory for SQLite database
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3008/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - smtp-mcp-server
  #   restart: unless-stopped

networks:
  default:
    name: smtp-mcp-network
