# Test CC and BCC functionality for SMTP MCP Server

Write-Host "🧪 Testing CC and BCC Support" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan

# Test email structure with CC and BCC
$testEmailData = @{
    to = @(
        @{ email = "primary@example.com"; name = "Primary Recipient" }
    )
    cc = @(
        @{ email = "cc1@example.com"; name = "CC Recipient 1" },
        @{ email = "cc2@example.com"; name = "CC Recipient 2" }
    )
    bcc = @(
        @{ email = "bcc1@example.com"; name = "BCC Recipient 1" },
        @{ email = "bcc2@example.com"; name = "BCC Recipient 2" }
    )
    subject = "Test Email with CC and BCC - SMTP MCP Server"
    html = @"
<h1>🎉 CC and BCC Test Email</h1>
<p>This email demonstrates the CC and BCC functionality of the SMTP MCP Server.</p>
<h2>✅ Features Tested:</h2>
<ul>
    <li><strong>Primary Recipient:</strong> primary@example.com</li>
    <li><strong>CC Recipients:</strong> cc1@example.com, cc2@example.com</li>
    <li><strong>BCC Recipients:</strong> bcc1@example.com, bcc2@example.com</li>
</ul>
<p>All recipients should receive this email, but:</p>
<ul>
    <li>CC recipients are visible to all other recipients</li>
    <li>BCC recipients are hidden from other recipients</li>
</ul>
<p><em>Generated by SMTP MCP Server</em></p>
"@
    text = "CC and BCC Test Email - This email demonstrates CC and BCC functionality. Primary: primary@example.com, CC: cc1@example.com, cc2@example.com, BCC: bcc1@example.com, bcc2@example.com"
}

Write-Host "`n📧 Email Structure:" -ForegroundColor Yellow
Write-Host "TO: $($testEmailData.to[0].email)" -ForegroundColor Green
Write-Host "CC: $($testEmailData.cc[0].email), $($testEmailData.cc[1].email)" -ForegroundColor Yellow
Write-Host "BCC: $($testEmailData.bcc[0].email), $($testEmailData.bcc[1].email)" -ForegroundColor Magenta

Write-Host "`n🔧 JSON Structure:" -ForegroundColor Cyan
$jsonData = $testEmailData | ConvertTo-Json -Depth 3
Write-Host $jsonData

Write-Host "`n📝 To send this email, use:" -ForegroundColor White
Write-Host "Invoke-RestMethod -Uri 'http://localhost:3008/api/send-email' -Method Post -Body `$jsonData -ContentType 'application/json'" -ForegroundColor Gray

Write-Host "`n✅ Your SMTP MCP Server supports:" -ForegroundColor Green
Write-Host "- Multiple CC recipients ✅" -ForegroundColor White  
Write-Host "- Multiple BCC recipients ✅" -ForegroundColor White
Write-Host "- Named recipients (email + name) ✅" -ForegroundColor White
Write-Host "- CC/BCC with single emails ✅" -ForegroundColor White
Write-Host "- CC/BCC with bulk emails ✅" -ForegroundColor White
Write-Host "- CC/BCC with template emails ✅" -ForegroundColor White
